//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixivClassifier.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixivClassifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无法复制到剪贴板，发生了异常:{0} 的本地化字符串。
        /// </summary>
        internal static string CopyToClipboardFailedDueTo {
            get {
                return ResourceManager.GetString("CopyToClipboardFailedDueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片路径不合法或不存在 的本地化字符串。
        /// </summary>
        internal static string PicturePathNotValidOrNotExist {
            get {
                return ResourceManager.GetString("PicturePathNotValidOrNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程数不是数字 的本地化字符串。
        /// </summary>
        internal static string ThreadCountIsNotValidNumber {
            get {
                return ResourceManager.GetString("ThreadCountIsNotValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线程数不在可接受范围内 的本地化字符串。
        /// </summary>
        internal static string ThreadCountOutOfAcceptableRange {
            get {
                return ResourceManager.GetString("ThreadCountOutOfAcceptableRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示最大可能同时执行的线程数，注意并不是说同时总是有这么多线程在执行，更高的线程数不一定会使处理更快 的本地化字符串。
        /// </summary>
        internal static string ThreadCountToolTip {
            get {
                return ResourceManager.GetString("ThreadCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时不是数字 的本地化字符串。
        /// </summary>
        internal static string TimeoutIsNotValidNumber {
            get {
                return ResourceManager.GetString("TimeoutIsNotValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时不在可接受范围内 的本地化字符串。
        /// </summary>
        internal static string TimeoutOutOfAcceptableRange {
            get {
                return ResourceManager.GetString("TimeoutOutOfAcceptableRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示获取pixiv信息时的最大超时限制，为0表示无超时限制，不能为负数 的本地化字符串。
        /// </summary>
        internal static string TimeoutToolTip {
            get {
                return ResourceManager.GetString("TimeoutToolTip", resourceCulture);
            }
        }
    }
}
